[project]
name = "gripper-2f85"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "RightOrNot", email = "jue1251665735@outlook.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
gripper-2f85 = "gripper_2f85:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
